ProyectoWeb1/urls.py
from django.conf import settings
from django.conf.urls import patterns,include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^',include('apps.aplicacion.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    #url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
    )

apps/aplicacion/urls.py
# -*- coding: utf-8
from django.conf.urls import patterns,include, url
from .views import *

urlpatterns = patterns('',
    url(r'^$',vista_inicio),
    url(r'^login/$',vista_login.as_view()),
    url(r'^usuario/$',vista_usuario),
    url(r'^usuario_ajax/$',vista_usuario_ajax),
    url(r'^nuevousuario_ajax/$',vista_nuevoUsuario_ajax),
    url(r'^usuario/provincia/$',vista_provincia.as_view()),
    url(r'^misdatos/$',vista_misDatos),
    url(r'^misdatos_ajax/$',vista_misDatos_ajax.as_view()),
    url(r'^misdatos_contra_ajax/$',vista_misDatos_contra_ajax.as_view()),
    #url(r'^misdatos/(?P<id_user>.*)/$',vista_misDatos),
    url(r'^productos/$',vista_productos),
    url(r'^productos/categorias/$',vista_productos_ajax.as_view()),
    url(r'^productos/categoria/(?P<id_categoria>.*)/$',vista_productos_categoria),
    url(r'^productos/detalle/(?P<id_producto>.*)/$',vista_producto_detalle),

    url(r'^productos/filtrar/$',vista_productos_filtrar.as_view()),

    url(r'^informacion/$',vista_informacion),

    url(r'^verificarFecha/$',vista_verificar_fecha.as_view()),

    url(r'^mispedidos/$',vista_mispedidos),
    url(r'^mispedidos/pedido/detalle/$',vista_pedidoDetalle.as_view()),
    url(r'^mispedidos/pedido/editar/$',vista_pedidoDetalleEditar.as_view()),
    url(r'^mispedidos/pedido/cancelar/$',vista_pedidoDetalleCancelar.as_view()),
    url(r'^mispedidos/pedido/imprimir/(?P<idPedido>.*)/$',imprimirPedido, name='imprimirPedido'),

    url(r'^pedido/imprimir/(?P<idPedido>.*)/$',imprimirPedido2, name='imprimirPedido2'),
    url(r'^reporte/imprimir/(?P<reporte>.*)/(?P<anio>.*)/(?P<mes>.*)/$',imprimirReporte),

    url(r'^gestionarpedidos/$',vista_gestionarpedidos),
    url(r'^gestionarpedidos/pedidosCedula/$',vista_gestionar_VerPedidos.as_view()),
    url(r'^gestionarpedidos/validarPedido/$',vista_gestionar_ValidarPedido.as_view()),

    url(r'^productos/pedir/$',vista_pedir.as_view()),

    url(r'^administrar/$',vista_administrar),
    url(r'^administrar-categoria/$',vista_administrar_categoria),
    url(r'^administrar-categoria/listaCategorias/$',vista_listaCategorias_admin.as_view()),
    url(r'^administrar-categoria/agregar/$',vista_administrar_categoria_agregar.as_view()),
    url(r'^administrar-categoria/editar/$',vista_administrar_categoria_editar.as_view()),
    url(r'^administrar-categoria/eliminar/$',vista_administrar_categoria_eliminar.as_view()),
    url(r'^administrar-producto/$',vista_administrar_producto),
    url(r'^administrar-producto/agregar/$',vista_administrar_producto_agregar.as_view()),
    url(r'^administrar-producto/listaProductos/$',vista_listaProductos_admin.as_view()),
    url(r'^administrar-producto/editar/$',vista_administrar_producto_editar.as_view()),
    url(r'^administrar-producto/eliminar/$',vista_administrar_producto_eliminar.as_view()),
    url(r'^administrar-usuario/$',vista_administrar_usuario),
    url(r'^administrar-usuario/estado/$',vista_administrar_usuario_estado.as_view()),
    url(r'^administrar-usuario/listaUsuarios/$',vista_administrar_usuario_listaUsuarios.as_view()),

    url(r'^reportes/$',vista_reportes),
    url(r'^reportes/reporte1/$',vista_reporte1.as_view()),
    url(r'^reportes/reporte2/$',vista_reporte2.as_view()),
    url(r'^reportes/reporte3/$',vista_reporte3.as_view()),
    url(r'^reportes/reporte4/$',vista_reporte4.as_view()),

    url(r'^salir/',cerrarSesion),
)

apps/aplicacion/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager



class Provincia(models.Model):
    nombre = models.CharField(max_length=30)

    def __unicode__(self):
        return self.nombre

class Ciudad(models.Model):
    nombre = models.CharField(max_length=30)
    provincia = models.ForeignKey(Provincia)

    def __unicode__(self):
        return self.nombre

class Rol(models.Model):
    nombre = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=100)
    clave = models.CharField(max_length=20)

    def __unicode__(self):
        return self.nombre


class UserManager(BaseUserManager, models.Manager):
    def _create_user(self, username, password, is_staff, is_superuser, **extra_fields):
        username = self.normalize_email(username)
        user = self.model(username=username, is_active=True, is_staff=is_staff,
                          is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using = self._db)
        return user

    def create_user(self, username, password, **extra_fields):
        return self._create_user(username, password, False, False, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        return self._create_user(username, password, True, True, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    username = models.EmailField(unique=True)
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    cedula = models.CharField(max_length=10,unique=True)
    telefono = models.CharField(max_length=10)
    fecha_nac = models.DateField()
    ciudad = models.ForeignKey(Ciudad)
    rol = models.ForeignKey(Rol)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    object = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['']

    def get_short_name(self):
        return self.nombres



class Categoria(models.Model):
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=100)

    def __unicode__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100)
    precio = models.FloatField()
    cantidad = models.CharField(max_length=10)
    categoria = models.ForeignKey(Categoria)

    def __unicode__(self):
        return self.nombre


class Foto(models.Model):
    imagen = models.ImageField(upload_to="fotos", default='/media/default.png')
    producto = models.ForeignKey(Producto)

class Pedido(models.Model):
    fecha_ini = models.DateField()
    fecha_fin = models.DateField()
    estado = models.CharField(max_length=10)
    usuario = models.ForeignKey(User)

class PedidoProducto(models.Model):
    pedido = models.ForeignKey(Pedido)
    producto = models.ForeignKey(Producto)
    cantidad = models.IntegerField()

class Publicidad(models.Model):
    descripcion = models.CharField(max_length=100)
    imagen = models.CharField(max_length=300)
    usuario = models.ForeignKey(User)

apps/aplicacion/views.py
# -*- coding: utf-8
import json
import datetime


from django.shortcuts import render, render_to_response
from django.http import request, HttpResponse, HttpResponseRedirect, Http404
from django.template import context, RequestContext
from django.views.generic import TemplateView, FormView, CreateView, UpdateView
import time
from reportlab.graphics.renderPDF import drawToString
from reportlab.platypus.para import Para
from .forms import *
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.core import serializers
from django.db.models import Q

from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Table, Image
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.pagesizes import A4


'''
class IndexView(TemplateView):
    form_class = UserRegistro_Form
    template_name = 'aplicacion/index.html'
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super(IndexView,self).form_valid(form)
'''


def vista_inicio(request):
    if request.method == 'POST':
        if 'botonLogeo' in request.POST:
            formLogin = UsuarioLogin(request.POST)

            if formLogin.is_valid():
                print 'Logeo validado'

                user = authenticate(username=formLogin.cleaned_data['username'],password=formLogin.cleaned_data['password'])

                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return HttpResponseRedirect('/')
                else:
                    print 'Usuario o contraseña incorrectos'

    else:
        formLogin = UsuarioLogin()

    return render(request, 'base.html', {'formularioLogeo': formLogin}, context_instance=RequestContext(request))


class vista_login(TemplateView):
     def get(self, request, *args, **kwargs):
        if request.is_ajax():

            nombreUser = request.GET['usuario']
            passUser = request.GET['password']


            formLogin = UsuarioLogin(nombreUser, passUser)

            print nombreUser


            datos=[]
            resul = {}

            if nombreUser=='' or passUser=='':
                resul['errorUsername']='Ambos campos son obligatorios'
                datos.append(resul)
            else:
                user = authenticate(username=nombreUser,password=passUser)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        resul['errorUsername']='yes'
                        datos.append(resul)
                        #return HttpResponseRedirect('/')
                else:
                    resul['errorUsername']='Usuario o Contraseña incorrectos'
                    datos.append(resul)



            data = json.dumps(datos)

            return HttpResponse(data, content_type='application/json')
        else:
            return Http404

class vista_misDatos_ajax(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            nombres=request.GET['nombres']
            apellidos=request.GET['apellidos']
            fecha_nac=request.GET['fecha_nac']
            ciudad=request.GET['ciudad']
            telefono=request.GET['telefono']
            username=request.GET['username']

            editUser = User.object.get(id=request.user.id)
            res={}
            res['co']=False

            if not editUser.username == username:
                try:
                    verCorreo = User.object.get(username=username)
                    print verCorreo

                    if verCorreo:
                        res['co']=True


                except:
                    print 'No hay'
                    editUser.username = username
                    editUser.save()
                    res['co']=False


            editUser.nombres = nombres
            editUser.apellidos = apellidos
            editUser.telefono = telefono
            editUser.fecha_nac = fecha_nac
            editUser.ciudad_id = ciudad

            print nombres, apellidos, fecha_nac, ciudad, telefono

            editUser.save()


            res['respuesta']='Cambios Guardados'

            data = json.dumps(res)

            return HttpResponse(data, content_type='application/json')
        else:
            return Http404


class vista_misDatos_contra_ajax(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            contraAc=request.GET['contraAc']
            contraNu=request.GET['contraNu']
            contraCo=request.GET['contraCo']

            editUser = User.object.get(id=request.user.id)

            res={}

            if editUser.check_password(contraAc):
                if contraNu == contraCo:
                    editUser.set_password(contraNu)
                    editUser.save()

                    res['respuesta']='Contraseña Cambiada'
                    res['valido']=True
                else:
                    res['respuesta']='Contraseñas nuevas no coinciden!'
                    res['valido']=False
            else:
                res['respuesta']='Contraseña Actual incorrecta!!'
                res['valido']=False



            #editUser.save()




            data = json.dumps(res)

            return HttpResponse(data, content_type='application/json')
        else:
            return Http404


def vista_misDatos(request):
    editUser = request.user

    datoCiudad = Ciudad.objects.get(id=editUser.ciudad_id)
    datoProvincia = Provincia.objects.get(id=datoCiudad.provincia_id)
    print datoProvincia.nombre



    if request.method == 'POST':
        formActualizar = UserRegistro_Form(request.POST)

        if 'botonActualizar' in request.POST:
            print formActualizar['cedula']
            formActualizar.username = 'xxxxxx@xxx.xxx'
            formActualizar.cedula = '1111111111'
            print formActualizar
            if formActualizar.is_valid():
                print 'Validado actualizar'

                #username=formActualizar.cleaned_data['username']
                #password=formActualizar.cleaned_data['password']
                nombres=formActualizar.cleaned_data['nombres']
                apellidos=formActualizar.cleaned_data['apellidos']
                #cedula=formActualizar.cleaned_data['cedula']
                fecha_nac=formActualizar.cleaned_data['fecha_nac'],
                ciudad=formActualizar.cleaned_data['ciudad']
                telefono = formActualizar.cleaned_data['telefono']
                #rol=formActualizar.cleaned_data['rol']

                #editUser = User.object.get(id=editUser.id)

                editUser.nombres = nombres
                editUser.apellidos = apellidos
                editUser.telefono = telefono
                editUser.fecha_nac = fecha_nac
                editUser.ciudad = ciudad
                '''
                editUser.apellidos = apellidos
                editUser.fecha_nac = fecha_nac
                editUser.ciudad = ciudad
                editUser.password = password
                '''

                editUser.save()

                return HttpResponseRedirect('/misdatos')
    else:
        formActualizar = UserRegistro_Form(instance=editUser)

    ctx = {
        'formActualizar':formActualizar,
        'nombreProvincia':datoProvincia.nombre

    }

    return render(request,'aplicacion/misDatos.html', ctx, context_instance=RequestContext(request))


def vista_usuario(request):
    if request.method == 'POST':
        form = UserRegistro_Form(request.POST)

        if form.is_valid():
            User.object.create_user(username=form.cleaned_data['username'],password=form.cleaned_data['password'],
                                    nombres=form.cleaned_data['nombres'],apellidos=form.cleaned_data['apellidos'],
                                    cedula=form.cleaned_data['cedula'],fecha_nac=form.cleaned_data['fecha_nac'],
                                    ciudad=form.cleaned_data['ciudad'],rol=form.cleaned_data['rol'],
                                    telefono=form.cleaned_data['telefono'])
            user = authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password'])
            if user is not None:
                    if user.is_active:
                        login(request, user)
                        return HttpResponseRedirect('/')
            return HttpResponseRedirect('/usuario')
    else:
        form = UserRegistro_Form()
    return render(request, 'aplicacion/usuario.html', {'form': form}, context_instance=RequestContext(request))

class vista_usuario2(FormView):
    form_class = UserRegistro_Form
    template_name = 'aplicacion/usuario.html'
    success_url = '/usuario/'

def vista_usuario_ajax(request):
    print 'formLlego'
    if request.is_ajax() and request.method == 'POST':
        form = UserRegistro_Form(request.POST)
        print 'formLlego2'

        errores = ''
        if form.is_valid():
            print 'valido'
            User.object.create_user(username=form.cleaned_data['username'],password=form.cleaned_data['password'],
                                    nombres=form.cleaned_data['nombres'],apellidos=form.cleaned_data['apellidos'],
                                    cedula=form.cleaned_data['cedula'],fecha_nac=form.cleaned_data['fecha_nac'],
                                    ciudad=form.cleaned_data['ciudad'],rol=form.cleaned_data['rol'])

            return HttpResponseRedirect('/usuario')
        else:
            print 'no valido'

templates/aplicacion/index.html
{% extends 'base.html' %}


{% block contenido %}

{% endblock %}

templates/aplicacion/misdatos.html
{% extends 'base.html' %}

{% block contenido %}
<div class="wrap">
    <div class="preview-page">
        <div class="contact-form">
            <h3>Datos Personales</h3>
            </div>
        </div>
    {% if user.is_authenticated %}
          <div class="formOtro">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
        	<div>
        		<ul>
                    <li><h2>MIS DATOS</h2></li>
                    <hr>
                    <li>{{formActualizar.cedula.label}}</li>
                    <li>{{formActualizar.cedula.errors}}</li>
                    <li>
                        <input id="id_cedula" maxlength="10" name="cedula" onkeypress="return solonumeros(event)"
                               placeholder="Cédula de Identidad" required="" type="text" disabled="" value="{{user.cedula}}">
                    </li>
                    <li>{{formActualizar.nombres.label}}</li>
                    <li>{{formActualizar.nombres.errors}}</li>
                    <li>{{formActualizar.nombres}}</li>
                    <li>{{formActualizar.apellidos.label}}</li>
                    <li>{{formActualizar.apellidos.errors}}</li>
                    <li>{{formActualizar.apellidos}}</li>
                    <li>{{formActualizar.username.label}}</li>
                    <li>{{formActualizar.username.errors}}</li>
                    <li>{{formActualizar.username}}</li>
                    <li>{{formActualizar.telefono.label}}</li>
                    <li>{{formActualizar.telefono.errors}}</li>
                    <li>{{formActualizar.telefono}}</li>
                    <li>{{formActualizar.fecha_nac.label}}</li>
                    <li>{{formActualizar.fecha_nac.errors}}</li>
                    <li>{{formActualizar.fecha_nac}}</li>
                    <li>{{formActualizar.ciudad.label}}</li>
                    <li>{{formActualizar.ciudad.errors}}</li>
                    <li>{{formActualizar.ciudad}}</li>
                    <li><label>Provincia:</label></li>
                    <li><input type="text" disabled value="{{nombreProvincia}}" id="id_provincia"></li>
                </ul>

                <p>
                    <hr>
                    <div align="center"><input type="button" name="botonActualizar" onclick="editarMisDatos()" value="Guardar Cambios"/> </div>
                </p>
          	</div>
            <hr>
              <hr>
      	</form>

              <form method="POST">

                  <div>
                      <ul>
                          <li><h2>Cambiar Contraseña</h2></li>
                          <hr>
                          <li><label>Contraseña Actual:</label></li>
                          <li><input id="contraAc" type="password" placeholder="Contraseña Actual"></li>
                          <li><label>Nueva Contraseña:</label></li>
                          <li><input id="contraNu" type="password" placeholder="Nueva Contraseña"></li>
                          <li><label>Confirmar Contraseña:</label></li>
                          <li><input id="contraCo" type="password" placeholder="Confirmar Contraseña"></li>
                      </ul>
                      <p>
                        <hr>
                        <div align="center"><input type="button" name="botonCambiarContrasena" onclick="editarPassword()"
                                                   value="Cambiar Contraseña"/> </div>
                      </p>
                  </div>
              </form>
          </div>
    <div id="mostrarMensajeMisDatos"></div>
     <script>
            $('#id_ciudad').change(function(){
                var ciu = $(this).val();

                $.ajax({
                    url: '/usuario/provincia/',
                    dataType: 'json',
                    data: {'ciudad_id':ciu},
                    type: 'GET'
                })
                .done(function (data){

                     var html = data.nombre
                     $('#id_provincia').val(html);

                })

                .fail(function(jqXHR, textStatus, errorThrown){
                            $('#id_provincia').val('');
                 });

            });

          function editarMisDatos(){
                var nombres = $('#id_nombres').val();
                var apellidos = $('#id_apellidos').val();
                var fecha_nac = $('#id_fecha_nac').val();
                var ciudad = $('#id_ciudad').val();
                var telefono = $('#id_telefono').val();
                var correo = $('#id_username').val();

                $.ajax({
                    url: '/misdatos_ajax/',
                    dataType: 'json',
                    data: {'nombres':nombres,'apellidos':apellidos,'fecha_nac':fecha_nac,'ciudad':ciudad,'telefono':telefono,'username':correo},
                    type: 'GET'
                })
                .done(function (data){
                    var htmlSeccion = ''
                    htmlSeccion = '<div class="ventana_flotante_mensaje">'+data.respuesta+'</div>'

                            if(data.co==true){
                                htmlSeccion = '<div class="ventana_flotante_mensaje">Este correo ya está registrado</div>'
                                $('#mostrarMensajeMisDatos').html(htmlSeccion);
                                $('#mostrarMensajeMisDatos').show();
                                setTimeout("$('#mostrarMensajeMisDatos').hide();", 2000);
                            }else{
                                $('#mostrarMensajeMisDatos').html(htmlSeccion);
                                $('#mostrarMensajeMisDatos').show();
                                setTimeout("$('#mostrarMensajeMisDatos').hide();", 2000);
                                setTimeout("location.reload()", 2000);
                            }



                })

                .fail(function(jqXHR, textStatus, errorThrown){
                 });

            }

            function editarPassword(){
                var contraAc = $('#contraAc').val();
                var contraNu = $('#contraNu').val();
                var contraCo = $('#contraCo').val();

                $.ajax({
                    url: '/misdatos_contra_ajax/',
                    dataType: 'json',
                    data: {'contraAc':contraAc,'contraNu':contraNu,'contraCo':contraCo},
                    type: 'GET'
                })
                .done(function (data){
                    var htmlSeccion = ''
                    htmlSeccion = '<div class="ventana_flotante_mensaje">'+data.respuesta+'</div>'
                    $('#mostrarMensajeMisDatos').html(htmlSeccion);
                        $('#mostrarMensajeMisDatos').show();
                        setTimeout("$('#mostrarMensajeMisDatos').hide();", 2000);
                    if(data.valido==true){
                        setTimeout("window.location.href = '/'", 2000);
                    }



                })

                .fail(function(jqXHR, textStatus, errorThrown){
                 });

            }
        </script>
    {% endif %}
    </div>
</div>
{% endblock %}

templates/aplicacion/usuario.html
{% extends 'base.html' %}

{% block contenido %}
<div class="wrap">
    <div class="preview-page">
        <div class="contact-form">
            <h3>Registro de Usuario</h3>
            </div>
        </div>
    {% if not user.is_authenticated %}
          <div class="formOtro">


        <form method="POST" id="formularioNuevoUsuario" enctype="multipart/form-data">
            {% csrf_token %}
        	<div>
        		<p>
                    <h2>Nuevo Usuario</h2>
                    <hr>
                </p>
                <ul>
                    <li>{{ form }}</li>

                </ul>


                <p>
                    <hr>
                    <div align="center"><input type="submit" value="Registrarse"/> </div>
                </p>
          	</div>
      	</form>
              </div>
          <div id="mierda"></div>
    <script>
        function enviarFormularioNuevoUsuario(){

            $.ajax({
                type: 'POST',
                url: '/nuevousuario_ajax/',
                dataType: 'json',
                async: true,
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    nombres: $('#id_nombres').val(),
                    apellidos: $('#id_apellidos').val(),
                    username: $('#id_username').val(),
                    cedula: $('#id_cedula').val(),
                    telefono: $('#id_telefono').val(),
                    password: $('#id_password').val(),
                    password2: $('#id_password2').val(),
                    fecha_nac: $('#id_fecha_nac').val(),
                    ciudad: $('#id_ciudad').val(),
                    rol: $('#id_rol').val(),
                    clave: $('#id_clave').val()
                }
            })
                    .done(function (data){
                        var html = ''
                        html += '<p>'+data.ErrorUsername+'</p>'
                        html += '<p>'+data.ErrorCedula+'</p>'

                        $('#mierda').html(html);
                    })
                    .fail(function(jqXHR, textStatus, errorThrown){
                         $('#mierda').html(errorThrown);
                    });
        }

    </script>

        <script>

            $('#id_rol').change(function(){
                var rol = $(this).val();
                var html= ''
                if (rol==2){
                    $('#id_clave').val('cliente01');
                }else{
                    $('#id_clave').val('');
                }


            });
        </script>
        <script>
            $('#id_ciudad').change(function(){
                var ciu = $(this).val();

                $.ajax({
                    url: '/usuario/provincia/',
                    dataType: 'json',
                    data: {'ciudad_id':ciu},
                    type: 'GET'
                })
                .done(function (data){

                     var html = data.nombre
                     $('#id_provincia').val(html);

                })

                .fail(function(jqXHR, textStatus, errorThrown){
                            $('#id_provincia').val('');
                 });

            });
        </script>
          <script>
              $('#botonRegistrar2').on('click',mostrarError);
              function mostrarError(){
                $.ajax({
                    success:  function(){
                            var html = '<p>{{form.errors}}</p>'

                           $('#mierda').html(html);
                       }
                   });
              }
          </script>
          <script>

              $('#formularioNuevoUsuario2').bind('submit',function(){


                   $.ajax({
                      data: $(this).serialize(),
                       url: '/usuario_ajax/',
                       type: 'POST',
                       dataType: 'json'


                   })
                  .done(function (data){
                         var htmlError = ''
                           if (data.errores.username){
                               htmlError += '<p>'+data.errores.username+'</p>'

                           }
                           $('#mierda').html(htmlError);
                    })
                    .fail(function(jqXHR, textStatus, errorThrown){
                         $('#mierda').html(errorThrown);
                    });
              });

          </script>


          {% endif %}
    </div>

</div>
{% endblock %}